import { PostDto,  } from "../types/Post";
import { Categories } from "./CategoryData";

export const PostData : PostDto []  = [
    {
        title: "Pirmas žingsnis",
        content: "<Parallel>\n<Box>\n<img src=\"https://i.imgur.com/eqOmdR3.jpeg\" style=\"width: 20vw; min-width: 330px;\"/>\n</Box>\n<Box>\n<p><strong>Labas, pirmakurse/-i!</strong></p>\n<p>Sveikinu žengus žingsnį į naują – buvimo studente/-u – etapą!</p>\n<p>Kaskart pradedant kažką nauja kyla daugybė skirtingų klausimų – kiekvienam tenka tai patirti. Bet galiu nudžiuginti – ši pradžia nebus tokia neaiški ir sunki. VU SA Tau parengė <strong>„Studentiško gyvenimo vadovą“</strong>!</p>\n<p>Čia rasi viską, ko Tau gali prireikti Universiteto aplinkos išnarpliojimui bei sklandžiam įsiliejimui į studijų procesą. Nuo svarbiausių <em>deadline’ų</em>, datų, iki Universiteto istorijos, nuo informacijos apie bendrabučius iki patarimų, ką daryti tam tikrose su studijomis susijusiose situacijose.</p>\n<p>Na, o jau susipažinus su studijomis Universitete, greitai atrasi erdves, kuriose galėsi semtis naujų patirčių bei siekti dar didesnio savarankiško tobulėjimo.</p>\n<p>Būk pasiruošęs ir sunkumams – jų kartais būna. Tačiau visos situacijos turi išeitį. O jei kartais ne išsyk pavyks ją rasti – visada gali kreiptis į Vilniaus universiteto Studentų atstovybę!</p>\n<p>Sėkmės studijų pradžioje!</p>\n<p><strong>V</strong>ieningai <strong>U</strong>ž <strong>S</strong>tudentų <strong>A</strong>teitį!</p>\n<p>VU SA prezidentė<br>Neda Žutautaitė</p>\n  </Box>\n</Parallel>",
        priority: 1,
        category: Categories["Pradedam!"], 
        subcategory: "", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Studentų himnas!",
        content: "<Parallel>\n <Box>\n<p>Taigi džiaukimės,</p>\n<p>kol esame jauni!</p>\n<p>Po malonios jaunystės,</p>\n<p>po sunkios senatvės</p>\n<p>mus priglaus žemė.</p>\n<p>Tegyvuoja akademija!</p>\n<p>Tegyvuoja profesoriai!</p>\n<p>Tegyvuoja kiekvienas narys!</p>\n<p>Tegyvuoja visi nariai!</p>\n<p>Visada teklesti!</p>\n<p>Tegyvuoja ir respublika,</p>\n<p>ir kurie ją valdo!</p>\n<p>Tegyvuoja mūsų valstybė,</p>\n<p>Malonė mecenatų,</p>\n<p>kurie mus čia globoja.</p>\n</Box>\n<Box>\n<p>Gaudeamus igitur,</p>\n<p>iuvenes dum sumus!</p>\n<p>Post iucundam iuventutem,</p>\n<p>post molestam senectutem</p>\n<p>nos habebit humus.</p>\n<p>Vivat academia!</p>\n<p>Vivant professores!</p>\n<p>Vivat membrum quodlibet!</p>\n<p>Vivant membra quaelibet!</p>\n<p>Semper sint in flore!</p>\n<p>Vivat et respublica</p>\n<p>et qui illam regunt!</p>\n<p>Vivat nostra civitas,</p>\n<p>Maecenatum caritas,</p>\n<p>Quae nos hic protegunt.</p>\n</Box>\n</Parallel>",
        priority: 2,
        category: Categories["Pradedam!"], 
        subcategory: "", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Studentų teisės",
        content: "<ul>\n<li>studijuoti pagal pasirinktą studijų programą;</li>\n<li>studijuoti pagal individualų studijų planą;</li>\n<li>studijuoti pagal daugiau negu vieną studijų programą;</li>\n<li>vertinti studijuojamų dalykų dėstymo ir studijų aprūpinimo kokybę;</li>\n<li>rinktis dėstytojus, jeigu tą patį dalyką dėsto keli dėstytojai;</li>\n<li>siūlyti savo baigiamojo darbo temą arba pasirinkti iš keleto pasiūlytų temų;</li>\n<li>atsiskaityti už darbus taikant alternatyvius būdus, jeigu turi negalią ar laikinąjį sveikatos sutrikimą, dėl kurių negali atsiskaityti nustatyta tvarka, o alternatyvus atsiskaitymo būdas užtikrina, kad bus pasiekti numatyti tikslai;</li>\n<li>kreiptis į aukštosios mokyklos administraciją, kad būtų įskaityti studijų toje pačioje arba kitoje Lietuvos arba užsienio aukštojoje mokykloje rezultatai;</li>\n<li>kreiptis į aukštosios mokyklos administraciją, Ginčų nagrinėjimo komisiją dėl teisėtų interesų pažeidimo bei Akademinės etikos komisiją dėl akademinės etikos pažeidimo;</li>\n<li>aukštosios mokyklos statuto nustatyta tvarka nutraukti ir (ar) atnaujinti studijas;</li>\n<li>išeiti akademinių atostogų ar sustabdyti studijas, neprarandant studento statuso;</li>\n<li>laisvai reikšti savo mintis ir pažiūras;</li>\n<li>dalyvauti aukštosios mokyklos valdyme;</li>\n<li>rinkti studentų atstovus ir būti išrinktam, laisvai jungtis į kitas asociacijas;</li>\n<li>naudotis įstatymų, Vilniaus universiteto statuto ir kitų teisės aktų nustatytomis teisėmis.</li>\n</ul>\n",
        priority: 3,
        category: Categories["Pradedam!"], 
        subcategory: "", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Studentų teisės",
        content: "<ul>\n<li>studijuoti pagal pasirinktą studijų programą;</li>\n<li>studijuoti pagal individualų studijų planą;</li>\n<li>studijuoti pagal daugiau negu vieną studijų programą;</li>\n<li>vertinti studijuojamų dalykų dėstymo ir studijų aprūpinimo kokybę;</li>\n<li>rinktis dėstytojus, jeigu tą patį dalyką dėsto keli dėstytojai;</li>\n<li>siūlyti savo baigiamojo darbo temą arba pasirinkti iš keleto pasiūlytų temų;</li>\n<li>atsiskaityti už darbus taikant alternatyvius būdus, jeigu turi negalią ar laikinąjį sveikatos sutrikimą, dėl kurių negali atsiskaityti nustatyta tvarka, o alternatyvus atsiskaitymo būdas užtikrina, kad bus pasiekti numatyti tikslai;</li>\n<li>kreiptis į aukštosios mokyklos administraciją, kad būtų įskaityti studijų toje pačioje arba kitoje Lietuvos arba užsienio aukštojoje mokykloje rezultatai;</li>\n<li>kreiptis į aukštosios mokyklos administraciją, Ginčų nagrinėjimo komisiją dėl teisėtų interesų pažeidimo bei Akademinės etikos komisiją dėl akademinės etikos pažeidimo;</li>\n<li>aukštosios mokyklos statuto nustatyta tvarka nutraukti ir (ar) atnaujinti studijas;</li>\n<li>išeiti akademinių atostogų ar sustabdyti studijas, neprarandant studento statuso;</li>\n<li>laisvai reikšti savo mintis ir pažiūras;</li>\n<li>dalyvauti aukštosios mokyklos valdyme;</li>\n<li>rinkti studentų atstovus ir būti išrinktam, laisvai jungtis į kitas asociacijas;</li>\n<li>naudotis įstatymų, Vilniaus universiteto statuto ir kitų teisės aktų nustatytomis teisėmis.</li>\n</ul>\n",
        priority: 4,
        category: Categories["Pradedam!"], 
        subcategory: "", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Studentų pareigos",
        content: "<p>Nepamiršk ir pareigų:</p>\n<ul>\n<li>vykdyti pasirinktos studijų programos ir studijų sutarties reikalavimus;</li>\n<li>laikytis studijų nuostatų, Vilniaus universiteto statuto ir kitų studijas reglamentuojančių aktų bei Lietuvos Respublikos įstatymų;</li>\n<li>laikytis bendrų moralės normų ir akademinės etikos;</li>\n<li>vykdyti universiteto ir akademinių kamieninių padalinių administracijos sprendimus;</li>\n<li>baigus studijas atsiskaityti su biblioteka ir kitais universiteto padaliniais bei Studentų atstovybe.</li>\n</ul>\n",
        priority: 5,
        category: Categories["Pradedam!"], 
        subcategory: "", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Studijų pradžia",
        content: "<h3>\n  Integracijos renginiai\n</h3>\n<p>\n  Kviečiame visus pirmakursius dalyvauti Vilniaus universiteto Studentų atstovybės kartu su Vilniaus universitetu organizuojamuose integracijos renginiuose #StudentAUK.\n</p>\n<p>\n  Mokslo metų pradžios programą ir daugiau informacijos gali rasti <a href=\"http://www.studentauk.vu.lt\">čia.</a>\n</p>\n<h3>\n Bendra informacija\n</h3>\n<p>2022 m. rudens semestras Vilniaus universitete prasideda rugsėjo 1 dieną.</p>\n<p>Per pirmas dvi semestro savaites bakalauro ir vientisųjų studijų pirmo kurso studentams (kuriems pasirenkamieji ir bendrieji universitetiniai studijų dalykai yra numatyti studijų plane) vyksta registracija į PD bei BUS dalykus:</p>\n<p>Dalykų (modulių) už 2021-2022 mokslo metų pavasario semestrą perlaikymas studentams vyks rugsėjo 2-16 dienomis.</p>\n<p>Savo <strong>tvarkaraščius</strong> gali rasti <a href=\"https://tvarkarasciai.vu.lt/\">čia.</a></p>\n<p>Daugiau informacijos apie studijas rudens semestre gali rasti <a href=\"https://www.vu.lt/covid-19/studentams/studijos-rudens-semestra\">čia</a> arba savo padalinio el. puslapyje.</p>\n<p><strong>Svarbiausias semestro datas</strong> gali rasti <a href=\"https://www.vu.lt/studijos/studentams/studiju-kalendorius#2020-2021-mokslo-metai\">čia</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio &ndash; akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>).</p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriaus akademiniu ar karjeros konsultantu (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia)</a>.</p>\n<h4>\n  Pirmoji paskaita\n</h4>\n<div class=\"panel-body toggle-content fusion-clearfix\">\n<p><span style=\"font-weight: 400;\"><strong>Pirmoji dalyko (modulio) paskaita yra labai svarbi.</strong> Jos metu dėstytojas turi pristatyti detalų dalyko (modulio) aprašą, kuriuo bus vadovaujamasi viso semestro metu:</span></p>\n<ol>\n<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Dalyko (modulio) programą;</span></li>\n<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Vertinimo ir egzaminavimo formą ir tvarką;</span></li>\n<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Vertinimo kriterijus;</span></li>\n<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Atsiskaitymo reikalavimus;</span></li>\n<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Privalomą literatūros sąrašą.</span></li>\n</ol>\n<p><span style=\"font-weight: 400;\">Pirmos paskaitos metu pateikta informacija semestro eigoje jokiu būdu negali būti keičiama. Studijų dalyko (modulio) aprašas turi būti skelbiamas VU informacinėje sistemoje.</span></p>\n<p><span style=\"font-weight: 400;\">Daugiau informacijos apie pirmąją dalyko (modulio) paskaitą gali rasti <a href=\"https://www.vu.lt/site_files/VU_studiju_nuostatai_suvestin%C4%97_redakcija_nuo_2018-09-25.pdf\" target=\"_blank\" rel=\"noopener noreferrer\">Vilniaus universiteto Studijų nuostatų</a> 25-ajame punkte.</span></p>\n<p><span style=\"font-weight: 400;\">Norėdamas pasikonsultuoti, gali kreiptis į savo <strong>padalinio socialinio-</strong></span><span style=\"font-weight: 400;\"><strong>akademinio proceso reikalų koordinatorių</strong> (kontaktus rasi <strong><a href=\"https://sgv.vusa.lt/konsultuokis/\" rel=\"noopener noreferrer\">čia</a></strong>).</span></p>\n<p><span style=\"font-weight: 400;\">Taip pat nebijok pasikonsultuoti su <strong>VU Studentų paslaugų ir karjeros skyriaus akademiniu ar karjeros konsultantu</strong> (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\" target=\"_blank\" rel=\"noopener noreferrer\">čia</a>).</span></p>\n</div>",
        priority: 6,
        category: Categories["Pradedam!"], 
        subcategory: "", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Akademinė etika",
        content: "<h4 >Akademinė etika</h4>\n<p>Vilniaus universitete puoselėjamos tradicijos ir vertybės, akademinės bendruomenės nuomonių įvairovė, atvirumas idėjoms, tarpusavio pagarba, pasitikėjimas ir tolerancija. Universitete yra vadovaujamasi studijų ir mokslo proceso skaidrumo, akademinio sąžiningumo, lygybės, nediskriminavimo, teisingumo, intelektinės nuosavybės apsaugos principais, todėl užtikrinamas dėstytojų nešališkumas vertinant studentus, pagarba studento privatumui ir jo nuomonės raiškai.</p>\n<p>Studentai, kaip ir visi Universiteto bendruomenės nariai, privalo puoselėti akademinio sąžiningumo principus, kuriuos pažeidžia nusirašinėjimas ir plagijavimas. Atsiskaitymų metu nusirašinėję arba savo darbus plagijavę studentai yra iš karto šalinami iš Universiteto.</p>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/BkAJtwQM21c\" frameborder=\"0\" allowfullscreen/></iframe>\n<p>Jei susidūrei su akademinės etikos pažeidimu, pavyzdžiui, jei dėstytojas paviešino egzamino ar kito atsiskaitymo įvertinimus, vietoje LSP numerio atskleisdamas studentų vardus ir pavardes, jei esi įsitikinęs, kad tave apšmeižė arba kitaip tyčiojosi dėstytojas ar kitas padalinyje dirbantis asmuo, gali kreiptis į Akademinės etikos komisiją, kuri veikia kiekviename KAP.</p>\n<p>Akademinės etikos nuostatai yra nurodyti <a href=\"https://www.vu.lt/site_files/Senatas_Taryba/Senatas/2018-04/Akademines_etikos_kodeksas.pdf\">Vilniaus universiteto Akademinės etikos kodekse</a></p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>).</p>\n<h4 id=\"akademin-s-etikos-komisija\">Akademinės etikos komisija</h4>\n<p>Kiekviename Kamieniniame akademiniame padalinyje (KAP) veikia Akademinės etikos komisija (AEK), kuri nagrinėja kreipimusis dėl akademinės bendruomenės narių, dirbančių ar studijuojančių tame Padalinyje, veiksmų, galimai pažeidžiančių akademinę etiką, pavyzdžiui, dėl nusirašinėjimo, plagijavimo, nesąžiningo studentų darbų vertinimo, atsiskaitymų įvertinimų paviešinimo, atskleidžiant studentų vardus ir pavardes, ir pan. </p>\n<p>Pareiškimą dėl akademinės etikos pažeidimo gali pateikti ne vėliau kaip per 1 mėnesį nuo tos dienos, kurią akademinės etikos pažeidimas buvo padarytas arba paaiškėjo.  </p>\n<p>Jei akademinės etikos pažeidimas, su kuriuo susidūrei, yra pernelyg glaudžiai susijęs su tavo KAP AEK nariais arba yra kitų priežasčių, dėl kurių gali kilti grėsmė nešališkam situacijos nagrinėjimui, gali kreiptis į VU Centrinę akademinės etikos komisiją. </p>\n<p>Daugiau informacijos gali rasti VU KAP Akademinės etikos komisijos nuostatuose  ir <a href=\"https://www.vu.lt/site_files/Senatas_Taryba/Senatas/2018-04/Centrines_akademines_etikos_komisijos_nuostatai.pdf\">VU Centrinės akademinės etikos komisijos nuostatuose</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n",
        priority: 7,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Akademinė etika", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Rotacija",
        content: "<p>Rotacija yra kas metus vykdomas procesas, kurio metu studentai yra reitinguojami pagal studijų rezultatus – studijų rezultatai yra vertinami priskiriant juos skirtingiems studijų lygmenims. </p>\n<p>2020–2021 studijų metų rudens semestre valstybės finansuojamo studento studijų pasiekimų lygmuo bus nustatomas ne vėliau kaip iki spalio 15 d.</p>\n<p>Geriausiai besimokantys studentai, studijuojantys valstybės nefinansuojamose vietose, rotacijos metu gali pereiti į valstybės finansuojamą vietą, tuo tarpu studentai, netenkinantys gerai besimokančio studento kriterijų, valstybės finansuojamą vietą gali prarasti.</p>\n<p>Gerai besimokantis studentas yra:</p>\n<ul>\n<li>Neturintis akademinių skolų;</li>\n<li>Įvykdęs visus studijų programai vertinamuoju laikotarpiu keliamus reikalavimus (dalyvavęs visuose egzaminuose ir įskaitose);</li>\n<li>Pasiekęs puikų arba tipinį pasiekimų lygmenį.</li>\n</ul>\n<p>Pasiekimų lygmenys:</p>\n<ul>\n<li><strong>Puikus</strong>: studentas neturi akademinių skolų ir vertinamojo laikotarpio svertinis pažymių vidurkis yra nuo 8 iki 10;</li>\n<li><strong>Tipinis</strong>: studentas neturi akademinių skolų ir vertinamojo laikotarpio svertinis pažymių vidurkis didesnis nei 5, tačiau nesiekia puikaus pasiekimų lygmens;</li>\n<li><strong>Slenkstinis</strong>: studentas neturi akademinių skolų ir vertinamojo laikotarpio svertinis pažymių vidurkis yra didesnis nei 4, tačiau nesiekia tipinio pasiekimų lygmens.</li>\n</ul>\n<p>Savo vietą rotacijoje gali sužinoti apsilankęs VU informacinėje sistemoje.</p>\n<p>Atsiradus laisvai VF vietai, KAP administracija apie tai privalo teikti informaciją padalinio internetinėje svetainėje ne vėliau kaip per 5 darbo dienas nuo vietos atsiradimo, taip pat per Vilniaus universiteto studijų informacinę sistemą siunčiant pranešimus valstybės nefinansuojamose vietose studijuojantiems studentams.</p>\n<p>Į laisvą vietą norintis pretenduoti studentas privalo pateikti prašymą kamieninio akademinio padalinio vadovui, o patvirtinus prašymą pasirašoma nauja studijų sutartis.</p>\n<p>Daugiau informacijos gali rasti <a href=\"https://vusa.lt/lt/duk-akademine-sritis\">VU SA internetiniame puslapyje</a> ir <a href=\"https://www.vu.lt/studijos/studentams/studiju-eiga/rotacija\">VU svetainėje</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>).</p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 8,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Rotacija ir studijų krepšelis", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Studijų krepšelis",
        content: "<p>Studijų krepšelis – tai valstybės teikiamas finansavimas studijoms.</p>\n<p>Valstybės biudžeto lėšos, skirtos studijų kainai valstybės finansuojamose studijų vietose apmokėti, arba jų dalis grąžinamos į valstybės biudžetą, jeigu asmenys nutraukia studijas savo noru.</p>\n<p>Jei nutrauksi studijas iki pirmojo semestro pabaigos, pinigų grąžinti nereikės (tai galioja tik pirmosios pakopos studijų programų studentams). Jei norėsi nutraukti studijas bet kurio vėlesnio semestro viduryje, teks valstybei grąžinti vieno semestro kainą, išskyrus:</p>\n<ul>\n<li>jei prašymą išeiti iš universiteto pateiksi iki naujo semestro pradžios ir neturėsi akademinių skolų;</li>\n<li>jei prašymą išeiti iš universiteto pateiksi būdamas akademinėse atostogose dėl ligos arba nėštumo ir gimdymo arba vaiko priežiūros atostogose.</li>\n</ul>\n<p>Daugiau informacijos apie studijų krepšelio grąžinimą gali rasti <a href=\"https://www.vu.lt/studijos/studentams/finansai/studiju-krepselio-grazinimas\">VU internetiniame puslapyje</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>).</p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 9,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Rotacija ir studijų krepšelis", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Valstybės (ne)finansuojamos vietos",
        content: "<p>Studentas, kuris mokosi valstybės nefinansuojamoje vietoje, gali pereiti į valstybės finansuojamą vietą, jei jo studijų programoje atsiranda laisva valstybės finansuojama vieta. </p>\n<p>Į atsiradusią laisvą valstybės finansuojamą vietą gali būti perkeltas tik toje pačioje studijų programoje, tame pačiame kurse (kuriame nepertraukiamai studijuoja tais pačiais metais, kaip ir finansavimo netekusio / pašalinto studento į pirmą kursą priimti studentai) studijuojantis asmuo.</p>\n<p>Laisvas valstybės finansuojamas vietas užima geriausi (pagal pažangumo eilę) tos pačios formos toje pačioje studijų programoje, tame pačiame kurse, valstybės nefinansuojamoje vietoje studijuojantys studentai, pateikę prašymą kamieninio akademinio padalinio vadovui ne vėliau kaip prieš 3 darbo dienas iki nustatytos datos atitinkamame semestre. </p>\n<p>Laisvos valstybės finansuojamos vietos užpildomos ne vėliau kaip:</p>\n<ul>\n<li>iki kovo 1 d. – perkeliant studentus po praėjusių mokslo metų rudens semestro į valstybės finansuojamas vietas, atsiradusias iki einamųjų metų vasario 25 d.</li>\n<li>iki rugsėjo 1 d. – perkeliant studentus po praėjusių mokslo metų pavasario semestro į valstybės finansuojamas vietas, atsiradusias iki einamųjų metų rugpjūčio 31 d.</li>\n<li>iki spalio 26 d. – perkeliant studentus į valstybės finansuojamas vietas, atsiradusias po vertinamojo laikotarpio studentams netekus valstybės finansavimo dėl prastų mokymosi rezultatų.</li>\n</ul>\n<p>Kamieninio akademinio padalinio administracija privalo teikti informaciją apie laisvas valstybės finansuojamas vietas padalinio interneto svetainėje ne vėliau kaip per 5 darbo dienas nuo laisvos valstybės finansuojamos vietos atsiradimo, taip pat per Vilniaus universiteto Studijų informacinę sistemą siunčiant pranešimus valstybės nefinansuojamiems studentams.  </p>\n<p>Studentai negali pretenduoti į laisvą valstybės finansuojamą vietą, jei netenkina gerai besimokančio studento statusą atitinkančių kriterijų, kurie yra:</p>\n<ul>\n<li>Neturintis akademinių skolų;</li>\n<li>Įvykdęs visus studijų programai vertinamuoju laikotarpiu keliamus reikalavimus (dalyvavęs visuose egzaminuose ir įskaitose);</li>\n<li>Pasiekęs puikų arba tipinį pasiekimų lygmenį.</li>\n</ul>\n<p>Daugiau informacijos gali rasti <a href=\"https://www.vu.lt/site_files/Reguliaminas/Laikinasis_rotacijos_aprasas_suvestin%C4%97_redakcija_nuo_2018-09-25.pdf\">Vilniaus universiteto studentų reitingavimo pagal studijų rezultatus ir rotacijos tvarkos apraše</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>).</p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 10,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Rotacija ir studijų krepšelis", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Apie stipendijas",
        content: "<h5 id=\"vilniaus-universitete-galima-gauti-ias-stipendijas-\">Vilniaus universitete galima gauti šias stipendijas:</h5>\n<ul>\n<li>Skatinamąją stipendiją; </li>\n<li>Vienkartinę socialinę stipendiją; </li>\n<li>Vienkartinę tikslinę stipendiją; </li>\n<li>Vardinę stipendiją; </li>\n<li>Profesinių pedagogikos studijų stipendiją; </li>\n<li>450 – mečio stipendiją; </li>\n<li>Užsieniečio studento stipendiją; </li>\n<li>Doktoranto stipendiją; </li>\n<li>Rezidento stipendiją; </li>\n<li>Socialinę stipendiją; </li>\n<li>Užsienio lietuvio stipendiją. </li>\n</ul>\n<p><strong>Norėdamas gauti stipendiją, nepamiršk užregistruoti savo banko sąskaitą. Tai gali padaryti pateikdamas prašymą VU informacinėje sistemoje.</strong> </p>\n<p>Daugiau informacijos apie šias stipendijas gali rasti <a href=\"https://www.vu.lt/studijos/studentams/finansai/stipendijos\">VU puslapyje</a>, <a href=\"https://www.vu.lt/site_files/Reguliaminas/Stipendij%C5%B3_nuostatai.pdf\">VU stipendijų nuostatuose</a> bei <a href=\"https://vsf.lrv.lt/lt/studentams\">Valstybinio studijų fondo puslapyje</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 11,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Stipendijos", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Skatinamoji stipendija",
        content: "<p>Skatinamoji stipendija yra skiriama bakalauro, magistrantūros, vientisųjų ir profesinių pedagogikos studijų studentams už geriausius mokymosi rezultatus. Ši stipendija negali būti skiriama pirmąjį studijų semestrą. </p>\n<p>Skatinamosios stipendijos negali gauti studentai turintys skolą (-ų) arba akademinę (-ių) skolą (-ų).  </p>\n<p>Skatinamosios stipendijos gali būti dviejų dydžių: 1,5 BSI (BSI – bazinė socialinė išmoka) ir  2,5 BSI t.y. 63 Eur ir 105 Eur. Skiriamos stipendijos dydis priklauso nuo studento vietos pažangumo eilėje. Ši stipendija yra skiriama vasario – liepos ir rugpjūčio – sausio mėnesiais. </p>\n<p>Norint gauti skatinamąją stipendiją, rašyti prašymo nereikia – ji skiriama automatiškai, tačiau nepamiršk studijų pradžioje savo VU IS paskyroje pateikti prašymą dėl banko sąskaitos užregistravimo.  </p>\n<p>Daugiau informacijos apie skatinamąsias stipendijas bei kitas stipendijas gali rasti <a href=\"https://www.vu.lt/site_files/Reguliaminas/Stipendij%C5%B3_nuostatai.pdf\">Vilniaus universiteto Stipendijų nuostatuose</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 12,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Stipendijos", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Vienkartinė socialinė stipendija",
        content: "<p>Vienkartinė socialinė stipendija gali būti skiriama studentams dėl materialinės ar  socialinės padėties pablogėjimo, artimųjų mirties, ligos, stichinių ar kitų nelaimių bei kitais atvejais. Šią stipendiją taip pat gali gauti studentas, kuris yra sustabdęs studijas arba esantis akademinėse atostogose. </p>\n<p>Vienkartinės socialinės stipendijos dydis yra nuo 2 BSI iki 12 BSI t.y. nuo 84 Eur iki 504 Eur. </p>\n<p>Norėdamas gauti vienkartinę socialinę stipendiją, turi VU IS pateikti prašymą bei reikiamus dokumentus: </p>\n<ul>\n<li>Pažymą apie savo šeimos sudėtį; </li>\n<li>Pažymą apie šeimos narių paskutinių 3 mėnesių darbo / individualios veiklos pajamas arba pažymą apie nedarbą; </li>\n<li>Pažymą apie savo paskutinių 3 mėnesių darbo / individualios veiklos pajamas arba pažymą apie nedarbą; </li>\n<li>Kitus dokumentus, įrodančius finansinės paramos poreikį. </li>\n</ul>\n<p>Daugiau informacijos apie vienkartines socialines stipendijas bei kitas stipendijas gali rasti <a href=\"https://www.vu.lt/site_files/Reguliaminas/Stipendij%C5%B3_nuostatai.pdf\">Vilniaus universiteto Stipendijų nuostatuose</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 13,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Stipendijos", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Vienkartinė tikslinė stipendija",
        content: "<p>Vienkartinė tikslinė stipendija gali būti skiriama bakalauro, magistrantūros, vientisųjų, profesinių pedagogikos studijų studentams, rezidentams ir doktorantams už gerus rezultatus: </p>\n<ul>\n<li>Sportinėje veikloje; </li>\n<li>Kultūrinėje veikloje; </li>\n<li>Mokslinėje veikloje; </li>\n<li>Visuomeninėje veikloje. </li>\n</ul>\n<p>Vienkartinės tikslinės stipendijos dydis yra nuo 1 BSI (BSI – bazinė socialinė išmoka) iki 15 BSI t.y. Nuo 42 EUR iki 630 EUR. </p>\n<p>Prašymą skirti vienkartinę tikslinę stipendiją, užpildytą veiklos lentelę bei kitus veiklą įrodančius dokumentus (pvz., diplomų, mokslinių publikacijų kopijas) gali teikti VU IS: rudens semestre iki spalio 25 dienos, o pavasario semestre iki kovo 25 dienos. </p>\n<p>Studentai, kurie yra sustabdę studijas ar yra pasiėmę akademines atostogas, taip pat gali teikti prašymą vienkartinei tikslinei stipendijai gauti. </p>\n<p>Vienkartinė tikslinė stipendija už tą patį nuopelną gali būti teikiama tik vieną kartą. </p>\n<p>Veiklos lentelės šabloną bei patarimus, kaip pildyti visuomeninės veiklos lentelę, gali rasti <a href=\"https://vusa.lt/lt/vienkartines-tikslines-stipendijos\">čia</a>.</p>\n<p>Daugiau informacijos apie vienkartines tikslines stipendijas bei kitas stipendijas gali rasti <a href=\"https://www.vu.lt/site_files/Reguliaminas/Stipendij%C5%B3_nuostatai.pdf\">Vilniaus universiteto Stipendijų nuostatuose</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 14,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Stipendijos", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Parama studentams su negalia",
        content: "<p>Visų rūšių išmokos neįgaliesiems teikiamos 45 proc. ir mažesnį darbingumo lygį turintiems studentams, kurie studijuoja pirmą kartą. </p>\n<p>Skiriamos šios finansinės pagalbos priemonės: </p>\n<ul>\n<li>išmokos individualiesiems poreikiams tenkinti (šiuo metu – 90,48 EUR kas mėnesį)  </li>\n<li><p>tikslinė išmoka studijų išlaidoms iš dalies kompensuoti – 124,80 EUR už kiekvieną semestrą, studijuojantiems valstybės nefinansuojamose vietose </p>\n</li>\n<li><p>tikslinė išmoka studijų prieinamumui didinti –  156,00 EUR kartą per mėnesį  </p>\n</li>\n<li><a href=\"http://vsf.lrv.lt/lt/administracines-paslaugos/socialiniu-stipendiju-skyrimas\">socialinė stipendija</a> – kartą per mėnesį skiriama 253,5 EUR dydžio išmoka. </li>\n</ul>\n<p>Finansinė pagalba specialiesiems poreikiams tenkinti ir tikslinės išmokos studijų prieinamumui didinti yra skiriamos vienam semestrui, tad prasidėjus naujam studijų semestrui nepamiršk iš naujo pateikti prašymą, jeigu nori ir toliau gauti paramą. </p>\n<p>Norėdami gauti finansinę pagalbą, studentai su negalia per 10 darbo dienų nuo kiekvieno semestro pradžios Vilniaus universiteto Studijų administravimo skyriui turi pateikti prašymą finansinei paramai gauti ir neįgaliojo pažymėjimo kopiją. Tai galima padaryti asmeniškai, elektroniniu paštu arba per „eStudento“ sistemą. Rudens semestrui – nuo einamųjų metų rugsėjo 1 d. iki spalio 16 d., pavasario semestrui – nuo einamųjų metų vasario 1 d. iki kovo 16 dienos. </p>\n<p>Daugiau informacijos apie tikslines išmokas galima rasti <a href=\"http://vsf.lrv.lt\">Valstybinio studijų fondo puslapyje</a>.</p>\n<p>Daugiau informacijos apie studijas ir negalią gali rasti <a href=\"https://www.vu.lt/studijos/studentams/studijos-ir-negalia\">VU internetiniame puslapyje</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 15,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Studentų finansai", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Studijų kainos kompensavimas",
        content: "<p>Studentas, studijuojantis valstybės nefinansuojamoje studijų vietoje, turi teisę susigrąžinti faktiškai sumokėtą studijų kainą. Už studijas sumokėta kaina gali būti kompensuojama geriausiais rezultatais atitinkamą studijų laikotarpį  baigusiems asmenims, kurie: </p>\n<ul>\n<li>neturi akademinių skolų; </li>\n<li>yra įvykdę visus studijų programai atitinkamais studijų metais keliamus reikalavimus; </li>\n<li>yra pasiekę puikų arba tipinį pasiekimų lygmenį. </li>\n</ul>\n<p>Kompensuojama per atitinkamą laikotarpį sumokėta studijų kaina ar studijų kainos dalis, bet ne didesnė kaip norminė studijų kaina. </p>\n<p>Daugiau informacijos apie studijų kainos kompensavimą gali rasti <a href=\"https://vsf.lrv.lt/lt/\">Valstybinio studijų fondo internetiniame puslapyje</a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 16,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Studentų finansai", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Valstybės remiamos paskolos",
        content: "<p>Valstybės remiamas paskolas gali gauti kasmet rudens ir (arba) pavasario semestrais. </p>\n<p>Studentai gali gauti trijų rūšių valstybės remiamas paskolas: </p>\n<ul>\n<li>Paskolą studijų kainai sumokėti (paskolos suma per vienerius studijų metus negali viršyti studento už einamuosius metus mokamos studijų kainos ar jos dalies) </li>\n<li><p>Paskolą gyvenimo išlaidoms (iki 1950 eurų per metus). Išmokama lygiomis dalimis kiekvieną mėnesį iki liepos 1 dienos (paskutinio kurso studentams – iki studijų pabaigos)  </p>\n</li>\n<li><p>Paskolą dalinėms studijoms (iki 2340 eurų per metus)  </p>\n</li>\n</ul>\n<p><strong>Visų rūšių valstybės remiamos paskolos teikiamos kasmet rudens semestre.</strong> Paskolos studijų kainai sumokėti, dalinėms studijoms pagal tarptautines (tarpžinybines) sutartis bei paskolos gyvenimo išlaidoms papildomai teikiamos ir pavasario semestre.  </p>\n<p>Studentas, norintis gauti paskolą, turi registruotis <a href=\"http://www.vsf.lt/\">Valstybinio studijų fondo interneto svetainėje</a> užpildydamas nustatytos formos prašymą – anketą. </p>\n<p>Paskolos grąžinimo pradžia – metai po studijų baigimo ar nutraukimo. Paskolos grąžinimo trukmė – 15 metų. </p>\n<p>Studijų laikotarpiu palūkanas už paskolas studijų kainai sumokėti bei dalinėms studijoms užsienyje gali dengti Valstybinis studijų fondas, nebent studijas baigtum, sustabdytum ar išeitum akademinių atostogų. Pildant prašymą-anketą būtina pažymėti varnelę ties punktu, kad nori dalyvauti konkurse dėl palūkanų apmokėjimo studijų laikotarpiu. Numatytais atvejais bei paprašęs paskolos gyvenimo išlaidoms, palūkanas turėsi sumokėti pats. </p>\n<p>Daugiau informacijos apie valstybės remiamas paskolas gali rasti <a href=\"https://vsf.lrv.lt/lt/studentams/vrpaskolos\">Valstybinio studijų fondo internetiniame puslapyje</a> arba <a href=\"https://vusa.lt/lt/paskolos\">Vilniaus universiteto Studentų atstovybės svetainėje</a>. </p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio socialinio – akademinio proceso reikalų koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>). </p>\n<p>Taip pat nebijok pasikonsultuoti su VU Studentų paslaugų ir karjeros skyriumi (daugiau informacijos <a href=\"https://karjera.lt/web/vilniaus-universiteto-karjeros-centras\">čia</a>).</p>\n",
        priority: 17,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Studentų finansai", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "LSP",
        content: "<p><strong>Kodėl verta gamintis?</strong> </p>\n<ul>\n<li>Tai yra studento statusą įrodantis dokumentas, aprašytas LR teisės aktuose; </li>\n<li>LSP suteikia daugybę nuolaidų ir lengvatų, pavyzdžiui, viešajam transportui, muziejams ir panašiai. Visas nuolaidas gali matyti <a href=\"https://lsp.lt/nuolaidos\">čia</a>;</li>\n<li>LSP reikalingas Universitete: dauguma operacijų VUB atliekama naudojantis LSP;</li>\n<li>Pažymėjimas reikalingas praeinant pro automatinius apsaugos vartelius ir t.t.;</li>\n<li>LSP kaina metams mažesnė negu kai kurių kitų komercinių studentiškų kortelių.</li>\n</ul>\n<p><strong>Iki LSP – tik 3 žingsniai!</strong></p>\n<ol>\n<li>Užsiregistruok <a href=\"http://www.lsp.lt/\"><strong>lsp.lt</strong></a> ir sek nurodymus;</li>\n<li>Sulauk pranešimo apie pagamintą LSP;</li>\n<li>Lauk, kol jis bus pristatytas Tau į namus!</li>\n</ol>\n<p><strong>Svarbu žinoti:</strong>• Registracijos metu įveskite teisingą savo asmens kodą! Jeigu suklydote – kreipkis į LSP koordinatorių!• LSP gamybą užsisakyti galima, kai Universitetas perduos Tavo studijų duomenis. Pirmakursiams studijų duomenys perduodami iki rugpjūčio pabaigos. Jeigu per 2 sav. nuo registracijos arba ilgiau negu rugpjūčio 31 d. nebūtų sutvarkyti studijų duomenys – kreipkis į LSP koordinatorių.<br>• Tik apmokėjus LSP gamybą jis pradedamas gaminti. LSP gamybos būseną galite sekti savo LSP paskyroje.<br>• LSP gamyba gali būti atšaukta, jeigu įkelta nuotrauka neatitinka keliamų reikalavimų. Todėl pasistenk įkelti ją teisingai iš pirmo karto, kad gamyba neužsitęstų!<br>• Rugsėjį, kol LSP yra gaminamas, gali naudotis miesto viešojo transporto lengvatomis Vilniuje ir Kaune su studijų pažyma (ją gali gauti iš savo KAP studijų skyriaus).<br>• LSP gamyba turėtų trukti ne ilgiau nei 1 darbo savaitę. Jeigu trunka ilgiau – nebijok kreiptis!</p>\n<p>Jeigu kiltų klausimų ar neaiškumų, susijusių su pažymėjimu, apsilankyk: <a href=\"https://vusa.lt/lt/lsp\"><strong>vusa.lt/lsp</strong></a>.</p>\n<p>Norėdamas pasikonsultuoti, gali kreiptis į savo padalinio LSP koordinatorių (kontaktus rasi <a href=\"https://sgv.vusa.lt/konsultuokis/\">čia</a>).</p>\n",
        priority: 18,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "Lietuvos studento pažymėjimas", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "E. tapatybių valdymo sistema",
        content: "<p><a href=\"https://id.vu.lt/\">id.vu.lt</a></p>\n<p>Užsiregistravęs e. tapatybių valdymo sistemoje, turėsi galimybę naudotis šiomis paslaugomis:</p>\n<ul>\n<li>prieiga prie Universiteto informacinės sistemos (VU IS);</li>\n<li>virtualia mokymosi aplinka (VMA);</li>\n<li>EDUROAM belaidžiu tinklu (Wi-Fi);</li>\n<li>VU virtualiu privačiu tinklu VPN;</li>\n<li>el. pašto dėžute ir kt.</li>\n</ul>\n<p>Visos centralizuotai administruojamos VU elektroninės paslaugos išvardintos <a href=\"https://www.vu.lt/it/epaslaugos/\">www.epaslaugos.vu.lt</a>. Čia rasi tiesioginio prisijungimo adresus, naudingas nuorodas ir svarbius pranešimus.</p>\n",
        priority: 19,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "VU informacinių technologijų paslaugų centras", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "VU elektroninis paštas ir el. pašto konferencijos",
        content: "<p><a href=\"https://webmail.vu.lt/\">webmail.vu.lt</a></p>\n<p>VU visiems studentams yra suteikiamos vardinės el. pašto dėžutės ir sudaromos sąlygos naudotis elektroninio grupinio susirašinėjimo paslauga – el. pašto konferencijomis.</p>\n<p>Savo universitetinį el. paštą gali integruoti į bet kurią kitą savo pašto dėžutę.</p>\n",
        priority: 20,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "VU informacinių technologijų paslaugų centras", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "VU informacinė sistema",
        content: "<p><a href=\"https://is.vu.lt/pls/klevas/logon\">is.vu.lt</a></p>\n<p>VU informacinėje sistemoje (VU IS) esanti virtuali studento darbo vieta eStudentas – tai visos studijų informacijos, susijusios su konkrečiu studentu, saugykla internete.</p>\n<p>Prisijungęs gali:</p>\n<ul>\n<li>sužinoti studijų programos planą, egzaminų pažymius, vietą geriausiai besimokančiųjų eilėje;</li>\n<li>gauti informaciją apie tau skirtas išmokas (stipendijas);</li>\n<li>atsispausdinti įmokų už studijas kvitus;</li>\n<li>pasirinkti pasirenkamuosius ir bendrųjų universitetinių studijų (BUS) dalykus;</li>\n<li>pateikti įvairius prašymus;</li>\n<li>dalyvauti universiteto organizuojamose apklausose ir kt.</li>\n</ul>\n",
        priority: 21,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "VU informacinių technologijų paslaugų centras", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Belaidės prieigos tinklas eduroam",
        content: "<p>Vilniaus universitete teikiama prieiga prie tarpautinio akademinių organizacijų belaidžio tinklo (Wi-Fi) „eduroam“ (angl. Education Roaming). Universiteto bendruomenė „eduroam“ gali naudotis nurodytose veikimo zonose VU ir kituose Lietuvos universitetuose bei „eduroam“ zonose užsienyje.</p>\n",
        priority: 22,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "VU informacinių technologijų paslaugų centras", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "VU virtuali mokymosi aplinka",
        content: "<p>Tai e. mokymosi terpė, kurioje galima rasti mokomąją medžiagą, atlikti savikontrolės testus, dalyvauti įvairiose mokomosiose veiklose, taip pat bendrauti forumuose, pokalbių kambariuose ar trumposiomis žinutėmis.</p>\n<p>VU virtuali mokymosi aplinka – į studentą orientuota mokymosi priemonė, kuria naudodamiesi tiek dėstytojas, tiek studentas gali glaudžiai bendradarbiauti ir įsisavinti studijuojamą dalyką. Šios aplinkos dėka studijos tampa lankstesnės ir labiau orientuotos į studento ir dėstytojo poreikius.</p>\n<p><strong>VMA privalumai ir galimybės:</strong></p>\n<ul>\n<li>visą mokymuisi skirtą informaciją gali rasti vienoje vietoje;</li>\n<li>patogesnis egzaminų ir tarpinių atsiskaitymų laikymas;</li>\n<li>bendravimas tarp dėstytojų ir studentų, konsultavimasis;</li>\n<li>grįžtamojo ryšio teikimas ir gavimas;</li>\n<li>video paskaitų peržiūra;</li>\n<li>paskaitos/seminaro interaktyvumas;</li>\n<li>egzamino ar tarpinio atsiskaitymo metu, užtikrina vertinio skaidrumą;</li>\n<li>studentas gali pasirinkti jam patogų studijų laiką, vietą, trukmę.</li>\n</ul>\n",
        priority: 23,
        category: Categories["Studijos VU: nuo A iki Ž"], 
        subcategory: "VU informacinių technologijų paslaugų centras", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Psichologinis konsultavimas",
        content: "<Parallel>\n  <Box>\n<p><strong>Psichologinio konsultavimo tikslas</strong> – padėti žmonėms išsiaiškinti, suprasti bei spręsti asmeninius arba tarpasmeninius su psichologine savijauta ar elgesiu susijusius sunkumus.</p>\n<p><strong>Kada kreiptis?</strong></p>\n<p>Dauguma į psichologą besikreipiančių žmonių neturi jokių psichikos sutrikimų. Psichologas padeda įveikti kasdieniniame gyvenime kylančias problemas. Dažniausiai pagalbos kreipiamasi dėl abejonių kylančių prieš priimant svarbius sprendimus, kankinančio vienišumo jausmo, nesutarimų su draugais ar artimaisiais, romantinių santykių rūpesčių, drovumo, asmeninių traumų, skyrybų, šeimos narių netekties ar sunkios ligos, problemų darbe ar moksle, piktnaudžiavimo alkoholiu ar kitomis narkotinėmis medžiagomis, užsitęsusio arba stipraus liūdesio, nerimo, trikdančių baimių, nekontroliuojamo valgymo.</p>\n<p><strong>Kur kreiptis?</strong></p>\n<p>Kviečiame kreiptis į <a href=\"https://www.fsf.vu.lt/apie-fsf/struktura/konsultavimo-ir-mokymu-centras-neakademinis/psichologines-paslaugos#kada-kreiptis\"><strong>Konsultavimo ir mokymų centrą.</strong></a></p>\n<p>VU studentams suteikiamos 4 nemokamos individualios psichologinės konsultacijos, kurias finansuoja Vilniaus universitetas. Galima lankyti ir grupinius užsiėmimus. Išnaudojus taikomas nuolaidas, konsultacijas galima tęsti pilna kaina.</p>\n<p>Konsultantų sąrašą gali rasti <a href=\"https://www.fsf.vu.lt/apie-fsf/struktura/konsultavimo-ir-mokymu-centras-neakademinis/psichologines-paslaugos#konsultantai\"><em>čia.</em></a></p>\n<p><strong>Rašyk mums:</strong> <a href=\"mailto:kmc@fsf.vu.lt\">kmc@fsf.vu.lt</a></p>\n<p><strong>Ateik:</strong> Universiteto g. 9/1, 116 kab.</p>\n<p><strong>Skambink:</strong> (8 5) 268 7254</p>\n<p>Atsižvelgiant į karantino laikotarpio patirtis, individualios konsultacijos vykdomos ne tik gyvų susitikimų metu, bet ir nuotoliniu būdu, jums patogia programėle (<em>Skype, Viber, Whatsapp, MS Teams</em> ir kt.).</p>\n    </Box>\n  <Box>\n    <img src=\"https://i.imgur.com/WnLp0C3.png\" style=\"width: 20vw; min-width: 330px;\">\n  </Box>\n  <Box>\n    <img src=\"https://www.fsf.vu.lt/dokumentai/nuotraukos/padek_vu.PNG\" style=\"width: 20vw; min-width: 330px;\">\n  </Box>\n</Parallel>",
        priority: 24,
        category: Categories["Psichologinis konsultavimas"], 
        subcategory: "", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "6 iššūkiai 1 kurse",
        content: "<h5 id=\"ilgalaikiai-projektai-ir-atsiskaitymai-pareikalaus-ger-laiko-planavimo-g-d-i-k-daryti-\">Ilgalaikiai projektai ir atsiskaitymai pareikalaus gerų laiko planavimo įgūdžių. Ką daryti?</h5>\n<p><strong>Nuo pat pradžių mokykis sistemingai:</strong> turėk darbų sąrašą su jų atlikimo terminais, įsivertink kiek valandų reikės kiekvienam darbui įgyvendinti. Būtinai numatyk laiko nenumatytiems darbams!</p>\n<h5 id=\"naujos-informacijos-bus-daug-tod-l-ir-klausim-gali-b-ti-daugiau-nei-atsakym-k-daryti-\">Naujos informacijos bus daug, todėl ir klausimų gali būti daugiau nei atsakymų. Ką daryti?</h5>\n<p><strong>Iki kitos paskaitos būtinai išsiaiškink visus neatsakytus klausimus, taip išvengsi spragų.</strong> Patikimiausi šaltiniai – dėstytojas ir privalomos literatūros sąrašas, kurį rasi dalyko apraše.</p>\n<h5 id=\"jei-pasirinkta-studij-sritimi-nema-ai-dom-jaisi-pirmieji-metai-gali-pasirodyti-per-lengvi-k-daryti-\">Jei pasirinkta studijų sritimi nemažai domėjaisi, pirmieji metai gali pasirodyti per lengvi. Ką daryti?</h5>\n<p><strong>Drąsiai prašyk dėstytojų papildomų užduočių ir projektų.</strong> Atlik <a href=\"https://www.vu.lt/studijos/studentams/praktika/praktika-lietuvoje\">savanorišką praktiką individualiai ar komandoje</a>. Pasidomėk <a href=\"https://www.vu.lt/studijos/studentams/studiju-eiga/gretutines-studijos\">gretutinėmis studijomis</a>. <a href=\"https://www.flf.vu.lt/kalbumokykla/apie\">Mokykis kalbų</a>. Išnaudok kitas universiteto siūlomas galimybes!</p>\n<h5 id=\"nauja-aplinka-atsiskaitymai-ir-kiti-i-kiai-kartais-kels-stres-kuris-trukdys-mokytis-k-daryti-\">Nauja aplinka, atsiskaitymai ir kiti iššūkiai kartais kels stresą, kuris trukdys mokytis. Ką daryti?</h5>\n<p><strong>Streso bus mažiau, jei pradėsi mokytis nuo pat pradžių (žr. 1-ą iššūkį)</strong> ir ugdysi savo atsparumą stresui. Rekomendacijas kaip tą padaryti, <a href=\"https://www.vu.lt/site_files/Vilniaus_universitetas._Stresuok_produktyviai.pdf\">rasi čia.</a></p>\n<h5 id=\"galb-t-prad-j-s-studijuoti-suprasi-kad-pasirinktos-studijos-ne-tau-k-daryti-\">Galbūt pradėjęs studijuoti suprasi, kad pasirinktos studijos – ne Tau. Ką daryti?</h5>\n<p>Jeigu taip atsitiktų, prieš priimdamas bet kokį sprendimą, <strong>susirink informaciją apie galimus sprendimo būdus</strong>. Studijų nutraukimas – ne vienintelė išeitis. Pasitark su specialistais – <a href=\"https://www.vu.lt/studijos/studentams/akademinis-studentams\">akademiniais</a> ir <a href=\"https://www.vu.lt/studijos/studentams/karjeros-paslaugos#individualios-konsultacijos\">karjeros konsultantais</a>.</p>\n<h5 id=\"daugyb-veiklos-galimybi-po-paskait-privers-pasukti-galv-kaip-i-sirinkti-kam-skirti-savo-laik-k-daryti-\">Daugybė veiklos galimybių po paskaitų privers pasukti galvą, kaip išsirinkti kam skirti savo laiką. Ką daryti?</h5>\n<p><strong>Ką veikti Vilniaus universitete, gali <a href=\"https://www.vu.lt/gyvenimas-universitete\">rasti čia</a>.</strong> Rinkdamasis atsižvelk į savo ateities tikslus, stiprybes ir silpnybes. Visa įgyta patirtis vėliau taps pranašumu darbo rinkoje!</p>\n",
        priority: 25,
        category: Categories["Akademinis ir karjeros konsultavimas"], 
        subcategory: "6 iššūkiai 1 kurse", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Akademinis konsultavimas",
        content: "<h5 id=\"studij-individualizavimas\">Studijų individualizavimas</h5>\n<p><strong>Kreipkis, jei nori studijas pritaikyti asmeniniams poreikiams:</strong> </p>\n<ul>\n<li>Domina individualaus studijų plano galimybė;</li>\n<li>Nori tinkamai pasirinkti pasirenkamuosius ar bendrųjų universitetinių studijų dalykus;</li>\n<li>Nežinai, ar gali rinktis gretutines studijas;</li>\n<li>Domiesi galimybe pakeisti studijų programą.</li>\n</ul>\n<h5 id=\"finansin-parama\">Finansinė parama</h5>\n<p><strong>Kreipkis, jei:</strong> </p>\n<ul>\n<li>Norėtum sužinoti apie Vilniaus universitete skiriamų stipendijų galimybes;</li>\n<li>Domina galimybė teikti prašymą valstybės remiamai paskolai gauti;</li>\n<li>Nori sužinoti daugiau apie studijų įmokų mokėjimą ir taikomas lengvatas (pvz., mokėjimą dalimis ar įmokos atidėjimą);</li>\n<li>Įdomu, kaip Universitete vykdomas studentų reitingavimas;</li>\n<li>Domiesi galimybe pereiti į valstybės finansuojamą vietą ar pretenduoti į studijų kainos kompensavimą.</li>\n</ul>\n<h5 id=\"studij-procesas\">Studijų procesas</h5>\n<p><strong>Kreipkis, jei:</strong></p>\n<ul>\n<li>Neaiški studijų dalyko vertinimo, egzaminų, jų perlaikymų ir skolų sistema;</li>\n<li>Domiesi studijų stabdymo ar akademinių atostogų galimybėmis ar svarstai apie  studijų sutarties nutraukimą.</li>\n</ul>\n<h5 id=\"pri-mimas-studijas\">Priėmimas į studijas</h5>\n<p><strong>Kreipkis, jei:</strong></p>\n<ul>\n<li>Reikia pagalbos pasirinkti norimą studijų programą (norint perstoti arba renkantis magistrantūros studijas)</li>\n<li>Neaiškus priėmimo procesas</li>\n</ul>\n<h5 id=\"kaip-konsultuotis-\">Kaip konsultuotis?</h5>\n<p><strong>Telefonu</strong> <strong>|</strong> (8–5) 219 3144</p>\n<p><strong>El. paštu |</strong> <a href=\"mailto:konsultavimas@vu.lt\">konsultavimas@vu.lt</a></p>\n<p><strong>Gyvai |</strong> Saulėtekio al. 9, III rūmai, 104 kab., Vilnius</p>\n<hr>\n<p><strong>Ar kainuoja?</strong> </p>\n<p>Ne, viskas nemokamai.</p>\n<hr>\n<p><strong>Kada kreiptis?</strong></p>\n<p>Bet kada, kai kyla klausimų!</p>\n",
        priority: 26,
        category: Categories["Akademinis ir karjeros konsultavimas"], 
        subcategory: "Akademinis konsultavimas", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Karjeros paslaugos",
        content: "<h5 id=\"individualios-karjeros-konsultacijos\">Individualios karjeros konsultacijos</h5>\n<p><strong>Kreipkis, jei:</strong></p>\n<ul>\n<li>Nori užsiimti papildoma veikla po studijų, tačiau nežinai, kas Tau labiausiai tiktų;</li>\n<li>Norėtum, kad specialistai suteiktų grįžtamąjį ryšį dėl Tavo CV, motyvacinio laiško, LinkedIn profilio;</li>\n<li>Svarstai apie darbą ar praktiką, bet nežinai, nuo ko pradėti;</li>\n<li>Patiri sunkumų studijuojant;</li>\n<li>Abejoji, ar tinkamai pasirinkai studijų programą.</li>\n</ul>\n<h5 id=\"karjeros-mokymai\">Karjeros mokymai</h5>\n<p><strong>Dalyvauk, jei:</strong></p>\n<ul>\n<li>Patinka mokytis grupėje;</li>\n<li>Turi su studijomis ir savo ateities karjera susijusių klausimų;</li>\n<li>Labiau patinka klausytis kompetentingų žmonių patarimų nei ieškoti informacijos savarankiškai;</li>\n<li>Patinka praktiniai užsiėmimai, kuriuose gali labiau pažinti save, parengti tinkamą CV, sužinoti darbo paieškos strategijas ar išmokti valdyti stresą.</li>\n</ul>\n<h5 id=\"karjera-lt\">karjera.lt</h5>\n<p><strong>Pasinaudok, jei:</strong></p>\n<ul>\n<li>Nori tobulėti savarankiškai;</li>\n<li>Ieškai darbo ar praktikos vietų;</li>\n<li>Nori atrasti praktinių patarimų ir kitos naudingos informacijos Tavo sėkmingai karjerai;</li>\n<li>Patinka spręsti testus ir daugiau sužinoti apie save.</li>\n</ul>\n<h5 id=\"kaip-konsultuotis-\">Kaip konsultuotis?</h5>\n<p><strong>Nuotoliniu būdu</strong> <strong>/</strong> <strong>Gyvai</strong> Saulėtekio al. 9, III rūmai, 104 kab., Vilnius</p>\n<hr>\n<p><strong>Kaip užsiregistruoti?</strong></p>\n<p><strong>El. paštu |</strong> <a href=\"mailto:karjeroscentras@vu.lt\">karjeroscentras@vu.lt</a></p>\n<p><strong>Telefonu |</strong> (8–5) 236 6253</p>\n<hr>\n<p><strong>Ar kainuoja?</strong> </p>\n<p>Ne, viskas nemokamai.</p>\n<hr>\n<p><strong>Kiek trunka?</strong></p>\n<p>&lt; 1 val.</p>",
        priority: 27,
        category: Categories["Akademinis ir karjeros konsultavimas"], 
        subcategory: "Karjeros paslaugos", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Praktika",
        content: "<h5 id=\"praktika-lietuvoje\">Praktika Lietuvoje</h5>\n<p><strong>Kreipkis, jei:</strong></p>\n<ul>\n<li>Domiesi praktikos Lietuvoje galimybėmis;</li>\n<li>Nori sužinoti, kuo skiriasi privaloma profesinė ir savanoriška praktika bei kada gali jas atlikti;</li>\n<li>Norėtum įgyti daugiau profesinės patirties, bet nežinai nuo ko pradėti.</li>\n</ul>\n<h5 id=\"praktika-u-sienyje\">Praktika užsienyje</h5>\n<p><strong>Kreipkis, jei:</strong></p>\n<ul>\n<li>Svarstai atlikti praktiką užsienyje ir nori sužinoti apie visas Vilniaus universiteto Tau siūlomas galimybes;</li>\n<li>Nori daugiau sužinoti apie praktikos užsienyje paieškos būdus;</li>\n<li>Manai, jog išvažiuoti atlikti praktiką užsienyje atrodo sudėtingas ir ilgas procesas.</li>\n</ul>\n<h5 id=\"sumanioji-praktika\">Sumanioji praktika</h5>\n<p><strong>Kreipkis, jei:</strong></p>\n<ul>\n<li>Norėtum atlikti praktiką ne vienas (-a), tačiau tarpkultūrinėje komandoje, kurioje susipažinsi su būsimais komunikacijos, informacinių technologijų, kalbotyros, ekonomikos ir kitų sričių specialistais;</li>\n<li>Norėtum daugiau sužinoti apie kūrybinio mąstymo metodiką „Design Thinking“ ir išmokti ją pritaikyti sprendžiant kilusias problemas;</li>\n<li>Nori iš arčiau pamatyti, su kokiais iššūkiais susiduria šiuolaikinis verslas.</li>\n</ul>\n<p><strong>Kaip konsultuotis?</strong></p>\n<p><strong>Telefonu</strong> | (8–5) 236 6011</p>\n<p><strong>El. paštu</strong> | <a href=\"mailto:praktika@vu.lt\">praktika@vu.lt</a></p>\n<p><strong>Gyvai</strong> | Saulėtekio al. 9, III rūmai, 104 kab., Vilnius</p>\n<hr>\n<p><strong>Ar kainuoja?</strong></p>\n<p>Ne, viskas nemokamai.</p>\n<hr>\n<p><strong>Kada kreiptis?</strong></p>\n<p>Bet kada, kai kyla klausimų</p>\n<p>Daugiau informacijos <a href=\"https://www.vu.lt/studijos/studentams/praktika\">čia</a></p>\n",
        priority: 28,
        category: Categories["Akademinis ir karjeros konsultavimas"], 
        subcategory: "Praktika", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
    {
        title: "Mentorystė",
        content: "<p><strong>Kreipkis į mentorių, jei:</strong></p>\n<ul>\n<li>Mąstai apie platesnę veiklą universitete;</li>\n<li>Svarstai, ką veiksi baigęs(-usi) studijas, ieškai daugiau informacijos apie darbo rinkos teikiamas galimybes;</li>\n<li>Dvejoji, ar rinktis mokslinę karjerą, ar pasukti į verslą;</li>\n<li>Neapsisprendi dėl aukštesnės pakopos studijų pasirinkimo;</li>\n<li>Turi profesinių tikslų ir svajonių, bet nežinai kaip jas įgyvendinti;</li>\n<li>Praradai motyvaciją toliau tęsti studijas, abejoji dėl savo pasirinkimo.</li>\n</ul>\n<h5 id=\"kaip-susisiekti-su-mentoriumi-\">Kaip susisiekti su mentoriumi?</h5>\n<ol>\n<li>Susirask mentorių platformoje: <a href=\"https://vu.lt/mentoriai\">vu.lt/mentoriai</a></li>\n<li>Užsiregistruok platformoje ir parašyk mentoriui, trumpai įvardindamas savo klausimą ar tikslą;</li>\n<li>Sulauk mentoriaus patvirtinimo;</li>\n<li>Tolimesnio bendravimo eigą ir komunikavimo priemones suplanuosite su mentoriumi individualiai;</li>\n<li>Kartu sieksite išsikeltų tikslų ir uždavinių;</li>\n<li>Bendravimas pabaigiamas, pasiekus išsikeltą tikslą bei suteikus abipusį grįžtamąjį ryšį.</li>\n</ol>\n<h5 id=\"kuo-pad-s-mentoryst-\">Kuo padės mentorystė?</h5>\n<ul>\n<li>Pažinsi mentoriaus profesinę aplinką;</li>\n<li>Įgysi daugiau pasitikėjimo savimi;</li>\n<li>Plėsi savo akiratį;</li>\n<li>Gausi vertingų patarimų sprendžiant su studijomis susijusias problemas;</li>\n<li>Megsi naujas pažintis ir plėsi savo kontaktų tinklą;</li>\n<li>Sieksi naujų akademinių ir asmeninių tikslų.</li>\n</ul>\n",
        priority: 29,
        category: Categories["Akademinis ir karjeros konsultavimas"], 
        subcategory: "Mentorystė", 
        isSponsored: false,
        moreLink: "",
        facultySpecific: "",
        language: "LT",
    },
]